### ISSUE TITLE
Display the release date in the application footer

### ISSUE THREAD

**Issue by mark-dce** [yalelibrary/YUL-DC#139]
**ACCEPTANCE**
- [x] The application footer displays the most recent deployment date 

NOTE: for our purpose, deployment = running the compose up command.

Here are a couple possible options for getting the date a "deployment" occurred

NOTE: see #143

**OPTION 1**
Have the compose script write the date into the container, e.g. something like
```
#docker-compose.yml
. . . 
  web:
    image: yalelibraryit/dc-blacklight:ecs
    command: /bin/sh -c "date -u +%FT%TZ > deploy-time.txt"  # <--- Something like this
   ports:
      - "3000:3000"
    volumes:
      - web:/home/app/webapp
. . .etc.
```

**OPTION 2**
Have CircleCI or whatever tool we use to deploy set and environment variable in the web container.
```
export LAST_DEPLOYMENT=`date -u +%FT%TZ`
```

**OPTION 2**
Use the aws ecs [describe-clusters](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-services.html) CLI tool to query cluster configuration

```
$ aws ecs describe-services --cluster bess-ecs --service bess-ecs --profile dce_main --query 'services[*].deployments[*].{TASK: taskDefinition,UPDATED: updatedAt}'
[
    [
        {
            "TASK": "arn:aws:ecs:us-east-1:884493977791:task-definition/bess-ecs:8",
            "UPDATED": 1589309026.515
        }
    ]
]
```
