### ISSUE TITLE
Fix job queue

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/YUL-DC#2560]
**Story**

Metadata updates for the same object are being added to the queue thousands of times.
```
  job_class: SetupMetadataJob
  job_id: 6136da2a-541f-4d25-b502-41b7eadbaea2
  provider_job_id: 
  queue_name: metadata
  priority: 0
  arguments:
  - _aj_globalid: gid://yul-dc-management/ParentObject/32204730
  - _aj_globalid: gid://yul-dc-management/BatchProcess/13334
  - _aj_globalid: gid://yul-dc-management/BatchConnection/20969668
```

**Acceptance**

- [x] Delete jobs from DB
