### ISSUE TITLE
Flaky test - rspec ./spec/requests/child_objects_spec.rb:43 with seed 25109

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#646]
To recreate - `rspec --seed 25109` 

```
Failures:

  1) /child_objects GET /new renders a successful response
     Failure/Error: get new_child_object_url

     NoMethodError:
       undefined method `to_key' for :user:Symbol
       Did you mean?  to_query
     # /usr/local/rvm/gems/ruby-2.6.6/gems/devise-4.7.2/lib/devise/models/authenticatable.rb:234:in `serialize_into_session'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/devise-4.7.2/lib/devise.rb:477:in `block (2 levels) in configure_warden!'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/session_serializer.rb:27:in `store'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/proxy.rb:187:in `set_user'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/test/helpers.rb:21:in `block in login_as'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden.rb:40:in `block in test_mode!'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/hooks.rb:15:in `block in _run_callbacks'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/hooks.rb:10:in `each'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/hooks.rb:10:in `_run_callbacks'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:52:in `_run_callbacks'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/proxy.rb:37:in `on_request'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:35:in `block in call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/rack/logger.rb:43:in `call_app'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rails_semantic_logger-4.4.4/lib/rails_semantic_logger/rack/logger.rb:28:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/honeybadger-4.7.0/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/honeybadger-4.7.0/lib/honeybadger/agent.rb:401:in `with_rack_env'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/honeybadger-4.7.0/lib/honeybadger/rack/error_notifier.rb:30:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/honeybadger-4.7.0/lib/honeybadger/rack/user_feedback.rb:31:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/honeybadger-4.7.0/lib/honeybadger/rack/user_informer.rb:21:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./spec/requests/child_objects_spec.rb:60:in `block (3 levels) in <top (required)>'
```
